export const GET_ALBUM_FAIL = "GET_ALBUM_FAIL";
export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";

export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";
export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";

export const GET_PHOTO_FAIL = "GET_PHOTO_FAIL";
export const GET_PHOTO_REQUEST = "GET_PHOTO_REQUEST";
export const GET_PHOTO_SUCCESS = "GET_PHOTO_SUCCESS";

export const GET_TODO_FAIL = "GET_TODO_FAIL";
export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";

export const GET_POST_FAIL = "GET_POST_FAIL";
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';